README.md
=> Update README.md to add the feedback survey

samples/BGV_country_db_lookup/runtest.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_centos.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_fedora.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_ubuntu.sh
Signed-off-By: Rosie Lickorish <rosielickorish@gmail.com>
=> Db lookup test

BuildDockerImage.sh
changing the curl commands to add a -k option if its running on a zOS platform. fully verified
=> Issue #9 zcx curl fix

Dockerfile.CENTOS-amd64.Toolkit, Dockerfile.FEDORA-amd64.Toolkit, Dockerfile.FEDORA-s390x.Toolkit, Dockerfile.UBUNTU-amd64.Toolkit, Dockerfile.UBUNTU-s390x.Toolkit
Additional code-server plugin to provide colourisation and list completion for CMake https://marketplace.visualstudio.com/items?itemName=twxs.cmake
=> Cmake extension included in toolkit docker files

BuildDockerImage.sh
=> Check boost tar

Dockerfile.CENTOS-amd64.Toolkit, Dockerfile.FEDORA-amd64.Toolkit, Dockerfile.FEDORA-s390x.Toolkit, Dockerfile.UBUNTU-amd64.Toolkit, Dockerfile.UBUNTU-s390x.Toolkit
Set a specific colour theme for the toolkit across all distros. #43
=> Specify color theme as dark

BuildDockerImage.sh, Dockerfile.ALPINE-amd64.Toolkit, Dockerfile.ALPINE-s390x.Toolkit, Dockerfile.ALPINE.HElib, FetchDockerImage.sh, GettingStarted.Advanced.md, GettingStarted.md, PersistData.sh, README.md, RunToolkit.sh, scripts/fhe_docker_jenkins_trigger_builds_alpine.sh
Add docker alpine linux support for x86 and s390 architectures.
=> alpine support

Dockerfile.ALPINE-amd64.Toolkit
Testing on Alpine x64 arch - country DB lookup demo works as expected.
=> Add cpptools and cmake extensions to alpine x64 arch

RunToolkit.sh, scripts/jenkins/fhe_artifactory_notification_script.sh, scripts/jenkins/fhe_docker_jenkins_change_logic.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_alpine.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_centos.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_fedora.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_ubuntu.sh
Created a script that notifies the fhe ibm private slack channel when a new internal artifactory docker image is available
=> Slack notification artifactory upload

scripts/jenkins/fhe_artifactory_notification_script.sh
Adding A Link to the git url commit that created the docker image in the Artifactory notification to slack
=> Slack notification tweaks

GettingStarted.md
Getting Started mentions needing an internet connection
=> Internet connection needed

Dockerfile.UBUNTU-amd64.Toolkit
Left an extra line in from when we were testing the cpptools solution, and its hitting that line, not finding the file it needs and failing.  So I removed it in the PR
=> Ubuntu Build is Failing, this is the fix

.clang-format, ConfigConstants.sh, DEPENDENCIES/simple_ml_helib/CMakeLists.txt, Dockerfile.CENTOS.HElib, samples/BGV_country_db_lookup/CMakeLists.txt, samples/credit_card_fraud/CMakeLists.txt, scripts/jenkins/fhe_docker_jenkins_trigger_builds_alpine.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_centos.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_fedora.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_ubuntu.sh
Update Helib version to 1.3.0,  
update CMakeLists.txt to compile using c++17, 
switch PowerTools to powertools in centos Dockerfile
Tested country db lookup and credit card fraud demo on each version of linux and each arch
=> Helib 1.3.0

BuildDockerImage.sh, ClearCachedDependencies.sh
changed the url of where we download ntl.tar file as well as added a clear dependencies script to make our lives easier when we test
Fixed bug #81
=> NTL URL Switch

README.md
=> adding section to readme about services

scripts/jenkins/fhe_docker_jenkins_trigger_builds_alpine.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_centos.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_fedora.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_ubuntu.sh
sorry forgot to point the scripts back to master
=> changing scripts back to point to master

scripts/jenkins/fhe_docker_jenkins_write_docs_script.sh
modifying script to handle committing with a valid comment, and not committing when nothing is there to commit
=> Jenkins write docs

DEPENDENCIES/ML-HElib/src/helayers/hebase/HeTraits.h, scripts/jenkins/fhe_docker_jenkins_write_docs_script.sh
=> Test trigger

DEPENDENCIES/ML-HElib/documentation/mainpage.dox, README.md, samples/BGV_world_country_db_lookup/BGV_world_country_db_lookup.cpp, samples/CKKS_credit_card_fraud/CKKS_credit_card_fraud_helib.cpp, samples/CKKS_credit_card_fraud/ClientServer.cpp, samples/mlhelib_tutorial/hebase_tutorial.cpp, samples/mlhelib_tutorial/tut_1_basics.cpp, samples/mlhelib_tutorial/tut_2_plaintexts.cpp, samples/mlhelib_tutorial/tut_3_io.cpp, samples/mlhelib_tutorial/tut_4_integers.cpp, scripts/jenkins/fhe_docker_jenkins_write_docs_script.sh
ADDING LINKs to Documentation in the readme and in the example files
=> Documentation links

scripts/jenkins/fhe_docker_jenkins_write_docs_script.sh
adding the HElib rendering to the write api docs script
=> adding the building of the HElib docs

ClearCachedDependencies.sh, ConfigConstants.sh, DEPENDENCIES/ML-HElib/make/CMakeLists.txt, scripts/jenkins/fhe_docker_jenkins_trigger_builds_alpine.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_centos.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_fedora.sh, scripts/jenkins/fhe_docker_jenkins_trigger_builds_ubuntu.sh
* points the toolkit to HElib 2.1.0
* removed treat errors are warnings flag from MLHelib Cmake
* re-factored the clear dependencies script to work on S390
=> Helib 2 1 0

BuildDockerImage.sh, README.md, samples/BGV_world_country_db_lookup/BGV_world_country_db_lookup.cpp, samples/BGV_world_country_db_lookup/README.md
Pointing our version of HELib to IBM-HElib
=> pointing to ibm-helib everywhere

BuildDockerImage.sh, Dockerfile.ALPINE.HElib, Dockerfile.CENTOS.HElib, Dockerfile.FEDORA.HElib, Dockerfile.UBUNTU.HElib
Addresses https://github.com/IBM/fhe-toolkit-linux/issues/28
=> Added USER_ID build arg to HElib build and HElib Dockerfiles

automation/DeployToHPVS.bashlib, automation/DeployToHPVS.conf, automation/DeployToHPVS.sh
Fixed the script so the resource plan id when input from the interactive wizard is now being written to the config file
=> Resource Plan ID wasn't being written to the config file

BuildDockerImage.sh, automation/DeployToHPVS.bashlib, automation/DeployToHPVS.conf, automation/DeployToHPVS.sh
Addresses https://github.com/IBM/fhe-toolkit-linux/issues/149
=> Added root/sudo check in build script

automation/DeployToHPVS.bashlib
Addresses https://github.com/IBM/fhe-toolkit-linux/issues/160
@boland25 feedback would be much appreciated
=> Added additional clarification to wizard

.vscode/settings.json, README.md, README_TOOLKIT.md
=> changed the readme to reflect that this repo is archvied
